### ISSUE TITLE
UnhandledPromiseRejectionWarning causes ROS to stop installing

### ISSUE THREAD

**Issue by nmerrill67** [betwo/github-setup-catkin#3] opened 2020-07-03 03:53 UTC
Hello, thanks for this great package! I tried it out today, following the example in the README, and on the action `Run betwo/github-setup-catkin@v1.0.0` in the log it says it's throwing a `UnhandledPromiseRejectionWarning`, and ROS stops installing. After that, it moves on to try and run the `catkin_make_isolated` command and fails with `ImportError: No module named catkin.builder`.  I am assuming clearly that the first "warning" is the issue, since ROS stops installing. 

Here is my c-cpp.yml:
```
name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: [ubuntu-18.04]
    strategy:
      fail-fast: false
      matrix:
        compiler: ["/usr/bin/g++"]
    steps:
    - uses: actions/checkout@v2
    - uses: betwo/github-setup-catkin@v1.0.0
      with:
        ros-version: 'melodic'
        workspace: '$GITHUB_WORKSPACE'
    - run: catkin_make_isolated -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
```

If I am using it wrong, please let me know!

**Comment by betwo** [comment] 2020-08-12 10:00
Hi @nmerrill67. Sorry for the late reply, I somehow missed this issue.
Looking into the problem now

**Comment by betwo** [comment] 2020-08-12 10:13
I have seen a regression with v1.0.0 -> some apt packages could not be installed because `python-rosdep` was no longer automatically installed.
This was fixed for me with pull request #2 (v.1.1.1).

Could you please try again, if you are still working on this? Thank you!

**Comment by betwo** [comment] 2020-08-12 13:46
I can now no longer reproduce the error with version v1.1.1.
Could you please check if you still have problems? Thank you!

**Comment by betwo** [comment] 2020-08-24 14:44
Closing this for now, seems to work okay

**Closed by betwo** 2020-08-24 14:44 UTC
